name: oldGamemode
version: 1.0
author: 3urobeat
main: org.herreurobeat.oldGamemode.Main
description: Use the old number system to change your gamemode!

commands:
  oginfo:
    description: What's this? (Help)
  gamemode:
    description: Change your gamemode.
  gm:
    description: Change your gamemode.